In [1]:
# Implementing Gauss-Jordan Elimination for a 3x3 matrix in Python to demonstrate the operation

import numpy as np

# Functions for matrix operations
def print_mat(mat):
    """Prints the matrix."""
    print("\n".join(["\t".join(map("{:.2f}".format, row)) for row in mat]))
    print()

def augment_mat(mat):
    """Creates the augmented matrix [A|I]."""
    n = len(mat)
    identity = np.eye(n)
    return np.hstack((mat, identity))

def swap_rows(mat, r1, r2):
    """Swaps two rows in the matrix."""
    mat[[r1, r2]] = mat[[r2, r1]]

def multiply_row(mat, row_idx, scalar):
    """Multiplies a row by a scalar."""
    mat[row_idx] *= scalar

def subtract_row(mat, source_idx, target_idx, coeff):
    """Subtracts a multiple of one row from another."""
    mat[target_idx] -= coeff * mat[source_idx]

def gauss_jordan(mat):
    """Performs Gauss-Jordan elimination."""
    n = len(mat)
    for i in range(n):
        # Pivot selection and normalization
        if mat[i, i] == 0:
            for j in range(i + 1, n):
                if mat[j, i] != 0:
                    swap_rows(mat, i, j)
                    break
        if mat[i, i] == 0:
            raise ValueError("Matrix is singular and cannot be inverted.")

        # Normalize the pivot row
        multiply_row(mat, i, 1 / mat[i, i])

        # Eliminate below
        for j in range(i + 1, n):
            subtract_row(mat, i, j, mat[j, i])

    # Back substitution for RREF
    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            subtract_row(mat, i, j, mat[j, i])

    return mat

# Input matrix
input_matrix = np.array([[0, 3, 2],
                         [1, 0, 2],
                         [0, 0, 1]], dtype=float)

# Augment the matrix
augmented_matrix = augment_mat(input_matrix)

# Perform Gauss-Jordan elimination
try:
    result_matrix = gauss_jordan(augmented_matrix)
    # Extract the inverse matrix
    inverse_matrix = result_matrix[:, len(input_matrix):]
    
    print("Original Matrix:")
    print_mat(input_matrix)
    
    print("Augmented Matrix:")
    print_mat(augmented_matrix)
    
    print("Reduced Row Echelon Form (RREF):")
    print_mat(result_matrix)
    
    print("Inverse Matrix:")
    print_mat(inverse_matrix)
except ValueError as e:
    print(e)


Original Matrix:
0.00	3.00	2.00
1.00	0.00	2.00
0.00	0.00	1.00

Augmented Matrix:
1.00	0.00	0.00	0.00	1.00	-2.00
0.00	1.00	0.00	0.33	0.00	-0.67
0.00	0.00	1.00	0.00	0.00	1.00

Reduced Row Echelon Form (RREF):
1.00	0.00	0.00	0.00	1.00	-2.00
0.00	1.00	0.00	0.33	0.00	-0.67
0.00	0.00	1.00	0.00	0.00	1.00

Inverse Matrix:
0.00	1.00	-2.00
0.33	0.00	-0.67
0.00	0.00	1.00



In [2]:
import numpy as np

def generate_invertible_matrix(size, min_value=0, max_value=100):
    """
    Generates a random invertible matrix of a given size with values between min_value and max_value.
    """
    while True:
        # Generate a random matrix with values between min_value and max_value
        matrix = np.random.randint(min_value, max_value + 1, (size, size))
        # Check if the matrix is invertible by calculating its determinant
        if np.linalg.det(matrix) != 0:
            return matrix

def main():
    matrices = {}
    for size in range(2, 11):  # Sizes from 2x2 to 10x10
        matrix = generate_invertible_matrix(size)
        matrices[size] = matrix
        print(f"\n{size}x{size} Invertible Matrix:")
        print(matrix)

if __name__ == "__main__":
    main()



2x2 Invertible Matrix:
[[76 76]
 [31 36]]

3x3 Invertible Matrix:
[[51 41  9]
 [15 40 72]
 [69 83  7]]

4x4 Invertible Matrix:
[[91 83 30 38]
 [89 52 55 20]
 [61 16 92 17]
 [73 67 65 19]]

5x5 Invertible Matrix:
[[93 36 42 11 88]
 [59 67 75 44 43]
 [45 60 34  2 94]
 [49 37 67 11 36]
 [19 32  9 69 89]]

6x6 Invertible Matrix:
[[95 52 52  4  9 53]
 [68 79 21 26 39 55]
 [31 21 18 56 93 13]
 [83 13 50  4 84 21]
 [72 29 74 89 15 20]
 [16 20 33 50 24 80]]

7x7 Invertible Matrix:
[[68 84 48 56 48 87 72]
 [34 91 82 19 38 14 64]
 [44 13 16 43 57 88 27]
 [20  5 88 34  4 42 88]
 [40 22 34 86 91 68 92]
 [91 45 76 44 63 85 51]
 [53 83 58 65  5 36 59]]

8x8 Invertible Matrix:
[[70  7 79 39 23 64 92 60]
 [49 73 23 93 39 84 89 11]
 [66  7 82 71 47 56 89 98]
 [49 43 41  1 11 99 35 79]
 [ 7  1 86  0 31 70 55 82]
 [ 2 70 88 16 68 26 19 99]
 [39 86 78 24 77 74 79 58]
 [10 17 36 19  8 48 32 77]]

9x9 Invertible Matrix:
[[12 21 82 37 87 28 79 91  5]
 [74 41 53 63 91 56 29 88 93]
 [25 33 87 43 77 47 88 93  